# Copyright 2022-2024 Chris Croome
#
# This file is part of the Webarchitects Firefox Ansible role.
#
# The Webarchitects Firefox Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Firefox Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Firefox Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
variables:
  ANSIBLE_CALLBACK_RESULT_FORMAT: "yaml"
  ANSIBLE_DISPLAY_SKIPPED_HOSTS: "0"
  ANSIBLE_FORCE_COLOR: "1"
  ANSIBLE_REMOTE_TMP: "/tmp"
  ANSIBLE_SHELL_ALLOW_WORLD_READABLE_TEMP: "1"
  DEBIAN_FRONTEND: "noninteractive"
  DEFAULT_MANAGED_STR: "Ansible managed"
  MOLECULE_VERBOSITY: "0"
  PY_COLORS: "1"
before_script:
  - whoami
  - pwd
  - chmod 700 $(pwd)
  - which ansible
  - ansible --version
  - which yamllint
  - yamllint --version
  - which molecule
  - molecule --version
  # libdbus-glib-1-2 is required by jammy
  - apt update
  - apt -yq install libdbus-glib-1-2
stages:
  - jammy
  - noble
  - bookworm
  - trixie
bookworm:
  image: registry.git.coop/webarch/containers/images/bookworm:20240326
  stage: bookworm
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test --all
trixie:
  image: registry.git.coop/webarch/containers/images/trixie:20240326
  stage: trixie
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test --all
jammy:
  image: registry.git.coop/webarch/containers/images/jammy:20240326
  stage: jammy
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test --all
noble:
  image: registry.git.coop/webarch/containers/images/noble:20240326
  stage: noble
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test --all
...
