# Copyright 2022-2024 Chris Croome
#
# This file is part of the Webarchitects Firefox Ansible role.
#
# The Webarchitects Firefox Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Firefox Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Firefox Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Firefox desktop file
  block:

    - name: Facts for the Firefox desktop file
      ansible.builtin.set_facts:
      firefox_desktop:
        "Desktop Entry":
          Actions: "new-window;new-private-window;open-profile-manager;"
          Categories: "GNOME;GTK;Network;WebBrowser;"
          Comment: "Browse the World Wide Web"
          Exec: "/usr/local/bin/{{ firefox_edition.pkg }} %u"
          Icon: "/usr/lib/{{ firefox_edition.pkg }}/browser/chrome/icons/default/default128.png"
          Keywords: "Internet;WWW;Browser;Web;Explorer;"
          MimeType: "application/json;application/pdf;application/rdf+xml;application/rss+xml;application/x-xpinstall;application/xhtml+xml;application/xml;audio/flac;audio/ogg;audio/webm;image/avif;image/gif;image/jpeg;image/png;image/svg+xml;image/webp;text/html;text/xml;video/ogg;video/webm;x-scheme-handler/chrome;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/mailto;"
          Name: "{{ firefox_edition.name }}"
          StartupNotify: true
          StartupWMClass: "{{ firefox_edition.pkg }}"
          Terminal: false
          Type: Application
          Version: "1.0"
          X-GNOME-FullName: "{{ firefox_edition.name }} Web Browser"
          X-MultipleArgs: false
        "Desktop Action new-window":
          Exec: "/usr/local/bin/{{ firefox_edition.pkg }} --new-window %u"
          Name: "New Window"
        "Desktop Action new-private-window":
          Exec: "/usr/local/bin/{{ firefox_edition.pkg }} --private-window %u"
          Name: "New Private Window"

    - name: Include firefox desktop file tasks
      ansible.builtin.include_tasks: desktop_edited.yml
      loop: "{{ firefox_desktop | dict2items }}"
      loop_control:
        loop_var: firefox_desktop_section
        label: "{{ firefox_desktop_section.key }}"

  tags:
    - firefox
...
