---
- name: Install and upgrade Firefox
  block:

    - name: Which Bash
      ansible.builtin.command: which bash
      check_mode: false
      changed_when: false
      register: firefox_bash

    # TODO GPG public key import

    - name: Include tasks for each version of Firefox
      include_tasks: version.yml
      loop: "{{ firefox_editions }}"
      loop_control:
        loop_var: edition
        label: "{{ edition.symlink }}"

  tags:
    - firefox
...
