# Copyright 2022-2024 Chris Croome
#
# This file is part of the Webarchitects Firefox Ansible role.
#
# The Webarchitects Firefox Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Firefox Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Firefox Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Skip the tasks in this role as firefox is false
  ansible.builtin.debug:
    msg: "The firefox variable need to be true for the tasks in this role to run."
  when: not firefox | bool
  tags:
    - firefox

- name: Install and upgrade Firefox
  block:

    - name: Validate Firefox variables
      ansible.builtin.include_tasks: validate.yml
      when: firefox_validate | bool

    - name: Include apt role local fact tasks if variables are not defined
      ansible.builtin.include_role:
        name: apt
        tasks_from: local_facts.yml
      when: >-
        ( ansible_local.dpkg.arch is not defined ) or
        ( ansible_local.gpg.version is not defined ) or
        ( ansible_local.bash.path is not defined )

    - name: Required packages present
      ansible.builtin.apt:
        pkg:
          - fonts-lmodern
          - fonts-stix
          - gnupg
          - python3-debian
          - xfonts-100dpi
          - xfonts-75dpi
          - xfonts-scalable
        state: present
        update_cache: true
        cache_valid_time: 0

    - name: Include the Firefox apt repo tasks
      ansible.builtin.include_tasks: apt.yml

    - name: Firefox editions present
      ansible.builtin.apt:
        pkg: "{{ firefox_pkg }}"
        install_recommends: true
        state: present
      vars:
        firefox_pkg: "{{ firefox_edition.pkg }}{% if firefox_lang != 'en' %}-l10n-{{ firefox_lang | lower }}{% endif %}"
      loop: "{{ firefox_editions }}"
      loop_control:
        loop_var: firefox_edition
        label: "{{ firefox_edition.pkg }}"

    - name: Include firejail tasks
      ansible.builtin.include_tasks: firejail.yml
      when: firefox_firejail | bool

  when: firefox | bool
  tags:
    - firefox
...
