---
- name: Install and upgrade Firefox
  block:

    - name: Requirements present
      ansible.builtin.apt:
        pkg:
          - gnupg
        state: present

    - name: Which Bash
      ansible.builtin.command: which bash
      check_mode: false
      changed_when: false
      register: firefox_bash

    - name: Mozilla Software Releases GPG key present
      ansible.builtin.copy:
        src: 61B7B526D98F0353.asc
        dest: /root/61B7B526D98F0353.asc
        mode: 0600

    - name: Mozilla Software Releases GPG key imported
      ansible.builtin.command: gpg --import /root/61B7B526D98F0353.asc
      register: firefox_gpg_import
      changed_when: ( "unchanged" not in firefox_gpg_import.stderr )

    - name: Debug GPG key import
      ansible.builtin.debug:
        var: firefox_gpg_import
        verbosity: 2

    - name: Import the Firefox versions JSON
      ansible.builtin.uri:
        url: https://product-details.mozilla.org/1.0/firefox_versions.json
        force: true
        return_content: true
        status_code:
          - 200
      register: firefox_versions

    - name: Debug Firefox versions type debug
      ansible.builtin.debug:
        msg: "{{ firefox_versions.json | type_debug }}"
        verbosity: 2

    - name: Debug Firefox versions JSON
      ansible.builtin.debug:
        var: line
        verbosity: 2
      loop: "{{ firefox_versions.json | dict2items }}"
      loop_control:
        loop_var: line
        label: "{{ line.key }}"

    - name: Include tasks for each version of Firefox
      include_tasks: version.yml
      loop: "{{ firefox_editions }}"
      loop_control:
        loop_var: edition
        label: "{{ edition.symlink }}"

    - name: Print the CHANGELOG
      ansible.builtin.debug:
        var: firefox_changelog
      when: firefox_changelog != []

  tags:
    - firefox
...
