---
- name: Install and upgrade Firefox
  block:

    # TODO GPG public key import

    - name: Include tasks for each version of Firefox
      include_tasks: version.yml
      loop: "{{ firefox_editions }}"
      loop_control:
        loop_var: edition
        label: "{{ edition.symlink }}"

  tags:
    - firefox
...
