---
- name: Install and upgrade Firefox
  block:

    - name: Requirements present
      ansible.builtin.apt:
        pkg:
          - gnupg
        state: present

    - name: Which Bash
      ansible.builtin.command: which bash
      check_mode: false
      changed_when: false
      register: firefox_bash

    - name: Mozilla Software Releases GPG key present
      ansible.builtin.copy:
        src: 61B7B526D98F0353.asc
        dest: /root/61B7B526D98F0353.asc
        mode: 0600

    - name: Mozilla Software Releases GPG key imported
      command: gpg --import /root/61B7B526D98F0353.asc
      register: firefox_gpg_import
      changed_when: ( "unchanged" not in firefox_gpg_import.stderr )

    - name: Debug GPG key import
      ansible.builtin.debug:
        var: firefox_gpg_import
        verbosity: 2

    - name: Include tasks for each version of Firefox
      include_tasks: version.yml
      loop: "{{ firefox_editions }}"
      loop_control:
        loop_var: edition
        label: "{{ edition.symlink }}"

    - name: Print the CHANGELOG
      debug:
        var: firefox_changelog

  tags:
    - firefox
...
