---
- name: Download and install Firefox
  block:

    - name: Check if Firefox is installed
      ansible.builtin.stat:
        path: "{{ firefox_bin }}/{{ edition.symlink }}"
        follow: true
      register: firefox_stat

    - name: Debug Firefox stat
      ansible.builtin.debug:
        var: firefox_stat
        verbosity: 1

    - name: Check Firefox installed version
      block:

        - name: Check installed version
          ansible.builtin.command: "{{ firefox_bin }}/{{ edition.symlink }} --version"
          check_mode: false
          changed_when: false
          register: firefox_version

        - name: Debug Firefox version
          ansible.builtin.debug:
            var: firefox_version
            verbosity: 1

      when: firefox_stat.stat.exists

    - name: Check URL
      ansible.builtin.uri:
        url: "https://download.mozilla.org/?product={{ edition.product }}&os={{ firefox_arch }}&lang={{ firefox_lang }}"
        method: HEAD
        status_code: 302
        follow_redirects: none
      check_mode: false
      changed_when: false
      register: firefox_head

    - name: Debug HEAD request
      ansible.builtin.debug:
        var: firefox_head
        verbosity: 1

    - name: Download Firefox
      block:

        - name: Download Firefox GPG signature
          ansible.builtin.get_url:
            url: "{{ firefox_head.location }}.asc"
            dest: "{{ firefox_download }}/{{ firefox_head.location | basename }}.asc"

        - name: Download Firefox GPG
          ansible.builtin.get_url:
            url: "{{ firefox_head.location }}"
            dest: "{{ firefox_download }}/{{ firefox_head.location | basename }}"

        - name: Check the GPG signature
          command: "gpg --verify {{ firefox_download }}/{{ firefox_head.location | basename }}.asc"
          check_mode: false
          changed_when: false
          register: firefox_gpg_verify

        - name: Debug GPG verify result
          ansible.builtin.debug:
            var: firefox_gpg_verify
            verbosity: 1

      when: >
        ( not firefox_stat.stat.exists )

  tags:
    - forefox
...
