---
- name: Download and install Firefox
  block:

    - name: Check if Firefox is installed
      stat:
        path: "{{ firefox_bin }}/{{ edition.symlink }}"
        follow: true
      register: firefox_stat

    - name: Debug Firefox stat
      debug:
        var: firefox_stat
        verbosity: 1

    - name: Check Firefox installed version
      block:

        - name: Check installed version
          command: "{{ firefox_bin }}/{{ edition.symlink }} --version"
          check_mode: false
          changed_when: false
          register: firefox_version

        - name: Debug Firefox version
          debug:
            var: firefox_version
            verbosity: 1

      when: firefox_stat.stat.exists

    - name: Check URL
      uri:
        url: "https://download.mozilla.org/?product={{ edition.product }}&os={{ firefox_arch }}&lang={{ firefox_lang }}"
        method: HEAD
        status_code: 302
        follow_redirects: none
      check_mode: false
      changed_when: false
      register: firefox_head

    - name: Debug HEAD request
      debug:
        var: firefox_head
        verbosity: 1

    - name: Download Firefox
      block:

        - name: Download Firefox GPG signature
          get_url:
            url: "{{ firefox_head.location }}.asc"
            dest: "/tmp/{{ edition.symlink | basename }}.asc"

        - name: Download Firefox GPG
          get_url:
            url: "{{ firefox_head.location }}"
            dest: "/tmp/{{ edition.symlink | basename }}"

      when: >
        ( not firefox_stat.stat.exists )

  tags:
    - forefox
...
