---
- name: Download and install Firefox
  block:

    - name: "Directory for downloads for {{ edition.name }} present"
      file:
        path: "{{ firefox_download }}/{{ edition.symlink }}"
        state: directory
        mode: 0700

    - name: "Check if {{ edition.name }} is installed"
      ansible.builtin.stat:
        path: "{{ firefox_bin }}/{{ edition.symlink }}"
        follow: true
      register: firefox_stat

    - name: "Debug {{ edition.name }} stat"
      ansible.builtin.debug:
        var: firefox_stat
        verbosity: 2

    - name: Check Firefox installed version
      block:

        - name: "Check installed version of {{ edition.name }}"
          ansible.builtin.command: "{{ firefox_bin }}/{{ edition.symlink }} --version"
          check_mode: false
          changed_when: false
          register: firefox_version

        - name: "Debug installed {{ edition.name }} version"
          ansible.builtin.debug:
            var: firefox_version
            verbosity: 2

      when: firefox_stat.stat.exists

    - name: "Check URL for {{ edition.name }}"
      ansible.builtin.uri:
        url: "https://download.mozilla.org/?product={{ edition.product }}&os={{ firefox_arch }}&lang={{ firefox_lang }}"
        method: HEAD
        status_code: 302
        follow_redirects: none
      check_mode: false
      changed_when: false
      register: firefox_head

    - name: "Debug HEAD request for URL for {{ edition.name }}"
      ansible.builtin.debug:
        var: firefox_head
        verbosity: 2

    - name: Download and install Firefox
      block:

        - name: "Download {{ edition.name }} GPG signature"
          ansible.builtin.get_url:
            url: "{{ firefox_head.location }}.asc"
            dest: "{{ firefox_download }}/{{ edition.product }}/{{ firefox_head.location | basename }}.asc"

        - name: "Download {{ edition.name }} GPG signature"
          ansible.builtin.get_url:
            url: "{{ firefox_head.location }}"
            dest: "{{ firefox_download }}/{{ edition.product }}/{{ firefox_head.location | basename }}"

        - name: "Check the {{ edition.name }} GPG signature"
          command: "gpg --verify {{ firefox_download }}/{{ edition.product }}/{{ firefox_head.location | basename }}.asc"
          check_mode: false
          changed_when: false
          register: firefox_gpg_verify
          failed_when: >
            ( firefox_gpg_verify.rc != 0 ) or 
            ( "Good signature from" not in firefox_gpg_verify.stderr )

        - name: "Debug {{ edition.name }} GPG verify result"
          ansible.builtin.debug:
            var: firefox_gpg_verify
            verbosity: 2

        - name: "Directory present to unarchive {{ edition.name }} into present"
          file:
            path: "{{ firefox_download }}/{{ edition.product }}/{{ firefox_head.location | basename | splitext | first | splitext | first }}"
            state: directory
            mode: 0700

        - name: "Unarchive {{ edition.name }}"
          ansible.builtin.unarchive:
            src: "{{ firefox_download }}/{{ edition.product }}/{{ firefox_head.location | basename }}"
            dest: "{{ firefox_download }}/{{ edition.product }}/{{ firefox_head.location | basename | splitext | first | splitext | first }}"
            remote_src: true

        - name: "Check if {{ edition.name }} has already been installed"
          stat:
            path: "{{ firefox_path }}/{{ edition.product }}"
            register: firefox_dest

        - name: "Move the old {{ edition.name }} out of the way and install the new version"
          shell: |
            set -e -o pipefail
            mv {{ firefox_path }}/{{ edition.product }} {{ firefox_path }}/{{ edition.product }}_$(date +%Y-%m-%d)
            mv {{ firefox_download }}/{{ edition.product }}/{{ firefox_head.location | basename | splitext | first | splitext | first }}/firefox {{ firefox_path }}/{{ edition.product }}   
          args:
            executable: "{{ firefox_bash.stdout }}"
          when: firefox_dest.stat.exists

        - name: "{{ edition.name }} symlink in place"
          file:
            state: link
            src: "{{ firefox_path }}/{{ edition.product }}/firefox"
            dest: "{{ firefox_bin }}/{{ edition.symlink }}"

      when: >
        ( not firefox_stat.stat.exists )

  tags:
    - forefox
...
