# Copyright 2022-2024 Chris Croome
#
# This file is part of the Webarchitects Firefox Ansible role.
#
# The Webarchitects Firefox Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Firefox Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Firefox Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
argument_specs:
  main:
    author: Chris Croome
    description: An Ansible role for installing Firefox on Linux x86_64 and i386.
    short_description: The main entry point for the Ansible role.
    options:
      firefox:
        type: bool
        required: true
        description: Run the tasks in this role.
      firefox_backports:
        type: str
        required: true
        description: Debian version backports string.
      firefox_desktop:
        type: dict
        required: true
        description: Dictionary of configuration for the Firefox Desktop file for Firejail.
      firefox_editions:
        type: list
        required: true
        description: A list of Firefox versions.
        options:
          name:
            type: str
            required: true
            description: The Firefox edition name.
          pkg:
            type: str
            required: true
            description: The Firefox edition package.
      firefox_firejail:
        type: bool
        required: true
        description: Install firejail.
      firefox_gpg_checksum:
        type: str
        required: true
        description: Internal Firefox GPG checksum.
      firefox_gpg_checksum_raw:
        type: str
        required: true
        description: Internal Firefox GPG checksum including sha256 prefix.
      firefox_gpg_fingerprints:
        type: list
        elements: str
        required: true
        description: A internal list of the fingerprints of the Firefox GPG key.
      firefox_gpg_fingerprints_query:
        type: str
        required: true
        description: A internal JMESPath query for the Firefox GPG fingerprints.
      firefox_gpg_url:
        type: str
        required: true
        description: A internal URL for the Firefox GPG key.
      firefox_lang:
        type: str
        required: true
        description: The Firefox language taken from the selet list at https://www.mozilla.org/en-GB/firefox/all/.
        choices:
          - ach
          - af
          - an
          - ar
          - ast
          - az
          - be
          - bg
          - bn
          - bo
          - br
          - bs
          - ca
          - cak
          - ca-valencia
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en-CA
          - en-GB
          - en-US
          - eo
          - es-AR
          - es-CL
          - es-ES
          - es-MX
          - et
          - eu
          - fa
          - ff
          - fi
          - fr
          - fy-NL
          - ga-IE
          - gd
          - gl
          - gn
          - gu-IN
          - he
          - hi-IN
          - hr
          - hsb
          - hu
          - hy-AM
          - ia
          - id
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - lij
          - lo
          - lt
          - ltg
          - lv
          - meh
          - mk
          - mr
          - ms
          - my
          - nb-NO
          - ne-NP
          - nl
          - nn-NO
          - oc
          - pa-IN
          - pl
          - pt-BR
          - pt-PT
          - rm
          - ro
          - ru
          - sat
          - sc
          - scn
          - sco
          - si
          - sk
          - skr
          - sl
          - son
          - sq
          - sr
          - sv-SE
          - szl
          - ta
          - te
          - tg
          - th
          - tl
          - tr
          - trs
          - uk
          - ur
          - uz
          - vi
          - wo
          - xh
          - zh-CN
          - zh-TW
      firefox_pkg:
        type: list
        elements: str
        required: true
        description: A list of Firefox packages.
      firefox_validate:
        type: bool
        required: true
        description: Use ansible.builtin.validate_argument_spec module to validate role argument specs.
...
