# Copyright 2022-2024 Chris Croome
#
# This file is part of the Webarchitects Firefox Ansible role.
#
# The Webarchitects Firefox Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Firefox Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Firefox Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Verify as root
  # become: true
  connection: local
  # gather_facts: true
  hosts:
    - localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    # - name: Run firefox --version
    #   ansible.builtin.command: /usr/local/bin/firefox --version
    #   check_mode: false
    #   changed_when: false
    #   register: molecule_firefox_version

    # - name: Set a fact for the firefox version
    #   ansible.builtin.set_fact:
    #     molecule_firefox_ver: "{{ molecule_firefox_version.stdout_lines[0] | ansible.builtin.split(' ') | last }}"

    # - name: Debug firefox --version
    #   ansible.builtin.debug:
    #     var: molecule_firefox_ver

    - name: Run firefox-beta --version
      ansible.builtin.command: /usr/local/bin/firefox-beta --version
      check_mode: false
      changed_when: false
      register: molecule_firefox_beta_version

    - name: Set a fact for the firefox-beta version
      ansible.builtin.set_fact:
        molecule_firefox_beta_ver: "{{ molecule_firefox_beta_version.stdout_lines[0] | ansible.builtin.split(' ') | last }}"

    - name: Debug firefox-beta --version
      ansible.builtin.debug:
        var: molecule_firefox_beta_ver

    - name: Run firefox-devedition --version
      ansible.builtin.command: /usr/local/bin/firefox-devedition --version
      check_mode: false
      changed_when: false
      register: molecule_firefox_devedition_version

    - name: Set a fact for the firefox-dev version
      ansible.builtin.set_fact:
        molecule_firefox_devedition_ver: "{{ molecule_firefox_devedition_version.stdout_lines[0] | ansible.builtin.split(' ') | last }}"

    - name: Debug firefox-dev --version
      ansible.builtin.debug:
        var: molecule_firefox_devedition_ver

    - name: Run firefox-nightly --version
      ansible.builtin.command: /usr/local/bin/firefox-nightly --version
      check_mode: false
      changed_when: false
      register: molecule_firefox_nightly_version

    - name: Set a fact for the firefox version
      ansible.builtin.set_fact:
        molecule_firefox_nightly_ver: "{{ molecule_firefox_nightly_version.stdout_lines[0] | ansible.builtin.split(' ') | last }}"

    - name: Debug firefox-nightly --version
      ansible.builtin.debug:
        var: molecule_firefox_nightly_ver
...
